ShoppingCartDemoApi/ShoppingCart/Models/Item.cs
namespace ShoppingCart.Models
{
    public class Item
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public string ImageName { get; set; }
    }
}

ShoppingCartDemoApi/ShoppingCart/Models/ItemViewModel.cs
using Microsoft.AspNetCore.Http;

namespace ShoppingCart.Models
{
    public class ItemViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public IFormFile Image { get; set; }
    }
}

ShoppingCartDemoApi/ShoppingCart/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using ShoppingCart.Models;
using System.Net.Http;

namespace ShoppingCart.Controllers
{
    public class ItemsController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        public ItemsController(IWebHostEnvironment hostEnvironment)
        {
            webHostEnvironment = hostEnvironment;
        }
        // GET: Items
        [AllowAnonymous]
        public IActionResult Index(string itemCategory, string searchString)
        {
            IEnumerable<Item> itemList, itemListDup;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;
            itemListDup = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            //accepts distinct category names
            HashSet<string> categoryQuery = new HashSet<string>();

            List<Item> items = new List<Item>();
            List<Item> newitems = new List<Item>();

            HashSet<int> keepIndex = new HashSet<int>();

            foreach (Item item in itemList)
            {
                categoryQuery.Add(item.Category);
                items.Add(item);
            }

            int i = 0;
            int x = 0;
            foreach(var item in items)
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    x = 1;
                    if (item.Title == searchString)
                    {
                        keepIndex.Add(i);
                    }
                }

                if (!string.IsNullOrEmpty(itemCategory))
                {
                    x = 1;
                    if (item.Category == itemCategory)
                    {
                        keepIndex.Add(i);
                    }
                }
                i++;
            }

            foreach(int j in keepIndex)
            {
                newitems.Add(items[j]);
            }

            var itemCategoryVM = new ItemCategoryViewModel();
            if (x == 1)
            {
                itemCategoryVM = new ItemCategoryViewModel
                {
                    Category = new SelectList(categoryQuery.ToList()),
                    Items = newitems
                };
            }
            else
            {
                itemCategoryVM = new ItemCategoryViewModel
                {
                    Category = new SelectList(categoryQuery.ToList()),
                    Items = items
                };
            }
            
            ViewBag.category = new List<String>(categoryQuery.ToList());

            if (LoggedUser.UserRole == "Admin")
            {
                return View("AdminProductList", itemCategoryVM);
            }

            return View(itemCategoryVM);
        }



        // GET: Items/Details/5
        public IActionResult Details(int? id)
        {
            IEnumerable<Item> itemList;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            if (id == null)
            {
                return NotFound();
            }

            foreach (Item item in itemList)
            {
                if (item.Id == id)
                {
                    Item kn = new Item
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Category = item.Category,
                        Price = item.Price,
                        ImageName = item.ImageName
                    };
                    return View(kn);
                }
            }

            return NotFound();
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        public IActionResult Create([Bind("Id,Title,Category,Price,Image")] ItemViewModel itemView)
        {
            
            Debug.WriteLine(itemView.Image);
            if (ModelState.IsValid)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + itemView.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    itemView.Image.CopyTo(fileStream);
                }

                Item item = new Item
                {
                    Id = itemView.Id,
                    Title = itemView.Title,
                    Category = itemView.Category,
                    Price = itemView.Price,
                    ImageName = uniqueFileName
                };

                HttpResponseMessage response = GlobalVariables.webApiClient.PostAsJsonAsync("Items", item).Result;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Items/Edit/5
        public IActionResult Edit(int? id)
        {
            IEnumerable<Item> itemList;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            if (id == null)
            {
                return NotFound();
            }

            foreach (Item item in itemList)
            {
                if (item.Id == id)
                {
                    ItemViewModel itemView = new ItemViewModel
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Category = item.Category,
                        Price = item.Price,
                    };
                    return View(itemView);
                }
            }

            return NotFound();
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id,Title,Category,Price,Image")] ItemViewModel itemView)
        {
            if (id != itemView.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + itemView.Image.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    itemView.Image.CopyTo(fileStream);
                }

                Item item = new Item
                {
                    Id = itemView.Id,
                    Title = itemView.Title,
                    Category = itemView.Category,
                    Price = itemView.Price,
                    ImageName = uniqueFileName
                };

               
               HttpResponseMessage response = GlobalVariables.webApiClient.PutAsJsonAsync("Items/"+id.ToString(), item).Result;
              
               return RedirectToAction(nameof(Index));
            }
            return View(itemView);
        }


        // GET: Items/Delete/5
        public IActionResult Delete(int? id)
        {
            IEnumerable<Item> itemList;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            if (id == null)
            {
                return NotFound();
            }

            foreach (Item item in itemList)
            {
                if (item.Id == id)
                {
                    Item kn = new Item
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Category = item.Category,
                        Price = item.Price,
                        ImageName = item.ImageName
                    };
                    return PartialView("DeletePartialView", item);
                }
            }

            return NotFound();
           
        }

        [HttpPost, ActionName("Delete")]
        // POST: Items/Delete/5
        public IActionResult DeleteConfirmed(int id)
        {
            
            HttpResponseMessage response = GlobalVariables.webApiClient.DeleteAsync("Items/" + id.ToString()).Result;
            return RedirectToAction(nameof(Index));
        }

    }
}

ShoppingCartDemoApi/ShoppingCart/Controllers/MyCartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using ShoppingCartDemo.Helpers;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using ShoppingCart.Models;
using System.Net.Http;

namespace ShoppingCart.Controllers
{
    
    public class MyCartItemsController : Controller
    {

        // GET: MyCartItems
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "Items");
            

            if (cart == null) {
                ViewBag.cart = cart;
                ViewBag.total = 0;
            }
            else
            {
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Price);
            }

            
            return View();
        }


        //displaying the details of the item
        // GET: Items/AddtoCart/5
        public IActionResult AddtoCart(int? id)
        {
            if (GlobalVariables.webApiClient.DefaultRequestHeaders.Authorization == null)
            {
                return RedirectToAction("Login", "Authenticate");
            }
            IEnumerable<Item> itemList;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            if (id == null)
            {
                return NotFound();
            }

            foreach (Item item in itemList)
            {
                if(item.Id == id)
                {
                    Item kn = new Item
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Category = item.Category,
                        Price = item.Price,
                        ImageName = item.ImageName
                    };
                    return View(kn);
                }
            }
            
            return NotFound();
            
        }

        public IActionResult ToCart([Bind("Id,Title,Category,Price,ImageName")] Item myCartItem)
        {
            Debug.WriteLine(myCartItem);

            if (SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "Items") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(myCartItem);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "Items", cart);
            }
            else
            {
                List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "Items");
                /*int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Product = productModel.find(id), Quantity = 1 });
                }*/
                cart.Add(myCartItem);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "Items", cart);
            }
            return RedirectToAction("Index", "Items");
        }





        //GET: MyCartItems/Delete/5

        public IActionResult Delete(int? id)
        {
            IEnumerable<Item> itemList;
            HttpResponseMessage response = GlobalVariables.webApiClient.GetAsync("Items").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<Item>>().Result;

            if (id == null)
            {
                return NotFound();
            }

            foreach (Item item in itemList)
            {
                if (item.Id == id)
                {
                    Item kn = new Item
                    {
                        Id = item.Id,
                        Title = item.Title,
                        Category = item.Category,
                        Price = item.Price,
                        ImageName = item.ImageName
                    };
                    return PartialView("MyCartItemDeletePartialView", kn);
                }
            }
            return NotFound();
        }

        // POST: MyCartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "Items");
            Debug.WriteLine(id);
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "Items", cart);
            return RedirectToAction("index");
        }


        private int isExist(int id)
        {
            List<Item> cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "Items");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Id == id)
                {
                    return i;
                }
            }
            return -1;
        }


    }
}

ShoppingCartDemoApi/ShoppingCart/Views/Items/AddtoCart.cshtml
@model ShoppingCart.Models.Item

@{
    ViewData["Title"] = "Add to Cart";
}

<h1>Add to Cart</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="MyCartItems" asp-action="AddtoCart">

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" readonly />

            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" readonly />

            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" readonly />

            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" readonly />

            </div>
            <div class="form-group">
                <input type="submit" value="Add to Cart" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShoppingCartDemoApi/ShoppingCart/Views/Items/AdminProductList.cshtml
@*Index page for items(connect with ItemsController)*@
@* here following @model gives access to the itemCategoryViewModel that the controller passed to the view*@
@*when we use the below line it says that this whole page using this model*@
@*this specifies the type of object that this view expects*@
@model ShoppingCart.Models.ItemCategoryViewModel



@{
    ViewData["Title"] = "Products List";
}


<div class="search-bottom">
    @*here the get command gives a the search query in the link*@
    <form asp-controller="Items" asp-action="Index" method="get">
        <p>
            <div class="sidenav">
                <a class="add-to-cart-btn add-to-cart-btn-outline-success" asp-action="Create">ADD</a>
                @foreach (var category in ViewBag.category)
                {
                    <input class="category-filter no-outline" type="submit" asp-for="ItemCategory" value=@category /><br />
                }
            </div>



            @*When filtered SearchString equals the given value in the input field*@
            <div class="title-search">
                <input class="title-search-input no-outline" placeholder="Search product name" type="text" name="SearchString" />
                <input class="filter no-outline" type="submit" value="" />
                <i class="fas fa-search"></i>
            </div>

        </p>
    </form>
    <br />
</div>

<div class="main">
    @foreach (var category in ViewBag.category)
    {
        <br />
        @foreach (var item in Model.Items)
        {
            @if (category == item.Category)
            {
                <h5>Category @category</h5>
                <hr />
                break;
            }
        }

        <div class="container">
            <div class="row h-200">
                @foreach (var item in Model.Items)
                {
                    @if (category == item.Category)
                    {

                        <div class="col-3">

                            <div class="product-card card-border card-border-success shadow-0 mb-3 text-center" style="width: 10rem">
                                <div class="card-body">
                                    <h7 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h7>
                                    <img class="mx-auto d-block" src="~/images/@item.ImageName"
                                         height="100" width="100" />
                                    <br />
                                    <p class="font-weight-bold">
                                        Rs.@Html.DisplayFor(modelItem => item.Price)
                                    </p>
                                    <a class="edit-delete-btn edit-delete-btn-outline-success" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    @*<a class="edit-delete-btn edit-delete-btn-outline-success" asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                                    @*<a href="#myModal" data-target="" class="edit-delete-btn edit-delete-btn-outline-success" data-toggle="modal" account-id="@item.Id">Delete</a>*@

                                    <button type="button" class="edit-delete-btn edit-delete-btn-outline-success" data-toggle="ajax-modal" data-target="#itemdeletemodal" data-url="@Url.Action($"Delete/{item.Id}")">Delete</button>

                                </div>
                            </div>
                        </div>

                    }

                }

            </div>
        </div>
    }
</div>

<div id="PlaceHolderHere"></div>

ShoppingCartDemoApi/ShoppingCart/Views/Items/Create.cshtml
@model ShoppingCart.Models.ItemViewModel


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Title" class="my-add-input no-outline" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Category" class="my-add-input no-outline" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Price" class="my-add-input no-outline" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" type="file" />

                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShoppingCartDemoApi/ShoppingCart/Views/Items/DeletePartialView.cshtml
@model ShoppingCart.Models.Item

<div id="modal" class="modal fade">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header flex-column">
                <div class="icon-box">
                    <i class="material-icons">&#xE5CD;</i>
                </div>
                <h4 class="modal-title w-100">Are you sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>Do you really want to delete item @Html.DisplayFor(model => model.Title)? This process cannot be undone.</p>
            </div>
            <div class="modal-footer justify-content-center">
                <form asp-controller="Items" asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
                <input type="submit" class="btn btn-secondary" value="Cancel" data-dismiss="modal">

            </div>
        </div>
    </div>
</div>

ShoppingCartDemoApi/ShoppingCart/Views/Items/Details.cshtml
@*Details page for items(connect with ItemsController)*@
@model ShoppingCart.Models.Item




@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ShoppingCartDemoApi/ShoppingCart/Views/Items/Edit.cshtml
@*Edit page for items(connect with ItemsController)*@
@model ShoppingCart.Models.ItemViewModel



@{
    ViewData["Title"] = "Product Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Title" class="my-add-input no-outline" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Category" class="my-add-input no-outline" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>
                </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <div class="title-search">
                    <input asp-for="Price" class="my-add-input no-outline" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" type="file" />

                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShoppingCartDemoApi/ShoppingCart/Views/Items/Index.cshtml
@using Microsoft.AspNetCore.Identity
@*@using ShoppingCart.Areas.Identity.Data*@

@model ShoppingCart.Models.ItemCategoryViewModel

@*@inject SignInManager<ApplicationUser> SignInManager*@

@{
    Layout = "_Layout";
}

@{
    ViewData["Title"] = "Products List";
}

<div class="search-bottom">
    @*here the get command gives a the search query in the link*@
    <form asp-controller="Items" asp-action="Index" method="get">
        <p>
            <div class="sidenav">
                @foreach (var category in ViewBag.category)
                {
                    <input class="category-filter no-outline" type="submit" asp-for="ItemCategory" value=@category /><br />
                }
            </div>
            
        

            @*When filtered SearchString equals the given value in the input field*@
        <div class="title-search">
            <input class="title-search-input no-outline" placeholder="Search product name" type="text" name="SearchString" />
            <input class="filter no-outline" type="submit" value=""/>
            <i class="fas fa-search"></i>
        </div>
        
        </p>
    </form>
    <br />
</div>

<div class="main">
    @foreach (var category in ViewBag.category)
    {
        <br />
        @foreach (var item in Model.Items)
        {
            @if (category == item.Category)
            {
                <h5>Category @category</h5>
                <hr />
                break;
            }
        }
        <div class="container">
            <div class="row h-200">
                @foreach (var item in Model.Items)
                {
                    @if (category == item.Category)
                    {

                        <div class="col-3">

                            <div class="product-card card-border card-border-success shadow-0 mb-3 text-center" style="width: 10rem">
                                <div class="card-body">
                                    <h7 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h7>
                                    <img class="mx-auto d-block" src="~/images/@item.ImageName"
                                         height="100" width="100" />
                                    <br />
                                    <p class="font-weight-bold">
                                        Rs.@Html.DisplayFor(modelItem => item.Price)
                                    </p>
                                    <a class="add-to-cart-btn add-to-cart-btn-outline-success" asp-controller="MyCartItems" asp-action="AddtoCart" asp-route-id="@item.Id">Add to Cart</a>
                                </div>
                            </div>
                        </div>

                    }

                }

            </div>
        </div>
    }
</div>